### ISSUE TITLE
Crash after JAOPCAAdditions update

### ISSUE THREAD

**Issue by binarybagel** [TheLMiffy1111/JAOPCAAdditions#2]
I had to downgrade to the last version manually to temporary fix it. Versions are in the log.

Crashlog:
[crash-2017-11-05_21.51.29-client.txt](https://github.com/TheLMiffy1111/JAOPCAAdditions/files/1444439/crash-2017-11-05_21.51.29-client.txt)

**Comment by TheLMiffy1111** [comment]
Fixed
