### ISSUE TITLE
[1.12.2] Crash after update

### ISSUE THREAD

**Issue by Diamondman121314** [TheLMiffy1111/JAOPCAAdditions#3]
I updated JAOPCAAdditions and it crashed, not much to say. 

https://pastebin.com/8cVTHD5d

I'm not sure if it's the same error as #2 but it looks similar.

**Comment by binarybagel** [comment]
"Caused by: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded."
Try adding this mod. Not 100% sure if that is the _only_ problem in the log though:
https://minecraft.curseforge.com/projects/notenoughids

**Comment by TheLMiffy1111** [comment]
This is not a bug of JAOPCA. Try adding NotEnoughIDs.
